CREATE DATABASE XPENSE
CREATE TABLE Users
(
id INT IDENTITY(1,1) PRIMARY KEY,
FirstName VARCHAR(250) NOT NULL,
UserPassword VARCHAR(250) NOT NULL,
UserEmail VARCHAR(250) NOT NULL,
LastName VARCHAR(250),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP

);
CREATE TABLE Category
(
id INT IDENTITY(1,1) PRIMARY KEY,
CategoryType VARCHAR(250) NOT NULL,
CategoryName VARCHAR(250) NOT NULL
);
CREATE TABLE Income
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT FOREIGN KEY REFERENCES Users(id),
    
    amount DECIMAL(20, 2) NOT NULL,
    
    date DATE NOT NULL,
    CategoryID INT FOREIGN KEY REFERENCES Category(id),
    description VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Expense
(
    id INT IDENTITY(1,1) PRIMARY KEY,
    user_id INT FOREIGN KEY REFERENCES Users(id),
	CategoryID INT FOREIGN KEY REFERENCES Category(id),
	description VARCHAR(255) NOT NULL,
	date DATE NOT NULL,
	amount DECIMAL(20, 2) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
   
   
);
CREATE TABLE Notifications
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	user_id INT FOREIGN KEY REFERENCES Users(id),
	Message VARCHAR(250),
	Time TimeStamp NOT NULL,
	Seen BIT
);
CREATE TABLE GOALS
(
	id INT IDENTITY(1,1) PRIMARY KEY,
	CategoryID INT FOREIGN KEY REFERENCES Category(id),
	Amount Decimal(20,2) NOT NULL,
	Description VARCHAR(250) NOT NULL,
);